clientes/urls.py
from django.urls import path
from . import views


app_name = 'clientes'

urlpatterns = [
    path('listar_clientes/', views.listar_clientes,name='listar_clientes'),
    path('registrar_novo_cliente/', views.registrar_novo_cliente,name='registrar_novo_cliente'),
    path('pesquisar_cliente/', views.pesquisar_cliente,name='pesquisar_cliente'),
    path('cliente/cliente/listar_clientes/deletar_cliente/<int:id>', views.deletar_cliente,name='deletar_cliente'),
    path('atualizar_cliente/<int:id>', views.atualizar_cliente,name='atualizar_cliente'),
]

emprestimo/urls.py
from django.urls import path
from .views import *


app_name = 'emprestimo'

urlpatterns = [
    path('listar_emprestimos/<str:filtro>', listar_emprestimos,name='listar_emprestimos'),
    path('registrar_novo_emprestimo/', registrar_novo_emprestimo,name='registrar_novo_emprestimo'),
    path('pesquisar_emprestimo/', pesquisar_emprestimo,name='pesquisar_emprestimo'),
    path('emprestimo/listar_emprestimos/deletar_emprestimo/<int:id>', deletar_emprestimo,name='deletar_emprestimo'),
    path('encerrar_emprestimo/<int:id>', encerrar_emprestimo,name='encerrar_emprestimo'),
    path('listar_emprestimos/todos_os_emprestimos', listar_emprestimos,name='pos_registro_emprestimo')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import urls as usuario_urls
from livro import urls as livros_urls
from clientes import urls as cliente_urls
from emprestimo import urls as emprestimo_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(usuario_urls)),
    path('livros/', include(livros_urls, namespace="livros")),
    path('cliente/', include(cliente_urls, namespace="cliente")),
    path('emprestimo/', include(emprestimo_urls, namespace="emprestimo")),      
]

livro/urls.py
from django.urls import path
from . import views


app_name = 'livros'

urlpatterns = [
    path('listar_livros/', views.listar_livros,name='listar_livros'),
    path('registrar_livro/', views.registrar_livro,name='registrar_livro'),
    path('pesquisar_livro/', views.pesquisar_livro,name='pesquisar_livro'),
    path('listar_livros/apagar_livro/<int:id>', views.apagar_livro,name='apagar_livro'),
    path('atualizar_livro/<int:id>', views.atualizar_livro,name='atualizar_livro'),
]

usuario/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', login_system,name='login'),
    path('salvar_usuario',salvar_usuario,name='salvar_usuario'),
    path('home',listar_usuarios,name='home'),
    path('logout', logout_system, name='logout'),
    path('deletar_usuario/<int:id>', deletar_usuario, name='deletar_usuario'),
    path('atualizar_usuario/<int:id>',atualizar_usuario, name='atualizar_usuario'),
]

usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

class authForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username","class": "form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Senha","class": "form-control"}))

class registerForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username","class": "form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email","class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password","class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password check","class": "form-control"}))
    
class updateForm(ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username","class": "form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email","class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password","class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password","class": "form-control"}))
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

usuario/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth import logout,login
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from livro import forms
from django.contrib import messages
import time


def is_logged(request,msg=""):
    return render(request,'listar_livros.html',{'conteudo_pesquisa_form':forms.BuscarLivroForm})


def login_system(request):
    if request.user.is_authenticated:
        return is_logged(request)
    
    if request.method == "POST":
        form = authForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return is_logged(request)
            else:
                messages.warning(request, "Usuario ou Senha Errados.")
        else:
            messages.warning(request, "Credenciais inválidas.")
    else:
        form = authForm()    
    return render(request, 'login.html', {'form': form})


def salvar_usuario(request):
    if request.method == "POST":
        form = registerForm(request.POST)
        try:
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                email = form.cleaned_data['email']
                
                if User.objects.filter(username=username).exists():
                    messages.warning(request, "Usuario já existe")
                else:
                    User.objects.create_user(username=username, password=password, email=email)
                    messages.success(request, "Salvo com sucesso")
                   
        except Exception as e:
            print(e)
            messages.warning(request, "Ocorreu um erro ao registrar o usuário")
    else:
        form = registerForm()
    return render(request, 'salvar_usuario.html', {'form': form})


def logout_system(request):
    logout(request)
    return redirect('login')

@login_required(login_url="login")
def deletar_usuario(request, id):
    try:
        user = User.objects.get(id=id)
        user.delete()
    except Exception as e:
        print(e)
    return redirect('home')


@login_required(login_url="login")
def atualizar_usuario(request,id):
    obj_user = None
    obj_user = User.objects.get(id=id)
    form = updateForm(request.POST or None, instance=obj_user)
    if request.method == "POST":
        if form.is_valid():
            form.save() 
            messages.success(request, "Atualizado com sucesso")
            return redirect('home')
    return render(request,'atualizar_usuario.html',{'form':form})
    
    
@login_required(login_url="login")
def listar_usuarios(request):
     return render(request,'tables.html',{'users':User.objects.all()})

usuario/templates/atualizar_usuario.html
{% extends 'base.html' %} {% block title %} Login {% endblock %}
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="card p-5">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
        {{ message }}
        </div>
     {% endfor %}
  <h1 class="mb-3">Atualizar Usuário</h1>
  <form action="" method="post">
    {% csrf_token %} {{ form.as_p }}
    <br />
    <div class="d-flex justify-content-center">
      <input
        type="submit"
        onclick="return confirm('Deseja realmente Atualizar?')"
        value="Atualizar"
        class="btn btn-primary btn-sm"
      />
    </div>
  </form>
</div>

{% endblock content %} {% block javascripts %}{% endblock javascripts %}

usuario/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      Biblioteca - {% block title %}{% endblock %} 
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800"rel="stylesheet"/>
    <link href="{% static 'usuario/css/black-dashboard.css' %}" rel="stylesheet"/>
    {% block stylesheets %}{% endblock stylesheets %}
  </head>
  <meta charset="UTF-8" />
  <title>Log In</title>
  <body >
    <div class="container-fluid bg-dark bg-gradient vw-100 vh-100 text-black" >

      {% include 'side-bar.html' %}
      {% block content %}{% endblock content %} 
      {% include 'modal_confirmacao.html' %}
    </div>
      <script src="{% static 'usuario/js/validar_isbn.js' %}"></script>
      <script src="https://kit.fontawesome.com/9958a2dab0.js" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
      <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% block javascripts %}{% endblock javascripts %}
  </body>
</html>

usuario/templates/footer.html
<footer class="footer px-5 py-4 fixed-bottom">
    <div class="copyright mx-auto float-none text-center">
        &copy; <a target="_blank" href="https://bit.ly/3fKQZaL">Lucas Lopes</a>
    </div>
</footer>

usuario/templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="d-flex flex-column">
      <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
        <div class="card">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
              {{ message }}
          </div>
          {% endfor %}

          <form role="form" method="post" action="">
            {% csrf_token %}

            <div class="card-body px-5 py-3">
              <div class="row">
                <div class="col-md-12 px-md-1">
                  <div class="form-group">
                    <label>Username</label>
                    {{ form.username }}
                  </div>
                </div>

                <div class="col-md-12 px-md-1">
                  <div class="form-group">
                    <label>Senha</label>
                    {{ form.password }}
                  </div>
                </div>
              </div>
            </div>
            <div class="card-footer text-center">
              <button
                type="submit"
                name="login"
                class="btn btn-fill btn-primary"
                href="{% url 'login' %}"
              >
                Entrar
              </button>
              <br /><br />
              <p>
                Não tem conta?
                <a href="{% url 'salvar_usuario' %}" class="text-primary"
                  >Registre-se</a
                >
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>
      function exibirMensagem(tipo, conteudo) {
        const messageContainer = document.getElementById('message-container');
        messageContainer.innerHTML = `<div class="alert alert-${tipo}" role="alert">${conteudo}</div>`;
      }
    </script>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

usuario/templates/modal_confirmacao.html
<div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content text-dark">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Confirmação</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body "  id="modal-body-text" >
         
        </div>
        <div class="modal-footer">
            <button type="button" id="btn-ok" class="btn btn-primary" >Entendi,mas desejo proseguir</button>
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Não</button>
        </div>
      </div>
    </div>
  </div>


<Script>

    function mostrarModal(mensagem) {
        let modal_body_text = document.getElementById('modal-body-text');
        let element_h3 = document.createElement('h3');
        element_h3.style.color = 'Gray';
        element_h3.textContent = mensagem;
        modal_body_text.appendChild(element_h3)
        resposta_modal = false;
        var myModal = new bootstrap.Modal(document.getElementById('staticBackdrop'));
        
        myModal.show();
        document.getElementById('btn-ok').addEventListener('click',
            async function(){
               myModal.hide();
               resposta_modal = true
            }
        )
        if (resposta_modal){
            alert(resposta_modal)
            return true;
        }else{
            return false;
        }
}
</Script>

usuario/templates/register.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

    <div class="content">
      <div class="container">
        <div class="row pt-5">
          <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
            <div class="card">
              <div class="card-header text-center py-4">
                {% if user.is_authenticated %}
                <h4 class="title">Cadastrar Novo Usuario</h4>
                {% else %}
                <h4 class="title">Inscreva-se</h4>
                {% endif %}
                <h6 class="card-category">
                  {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                  {% else %}
                  <span> Informe seus dados </span>
                  {% endif %}
                </h6>
              </div>

              {% if success %}

              <div class="card-footer text-center">
                <a href="{% url 'login' %}" class="btn btn-fill btn-primary">Login</a>
              </div>
              {% else %}
              <form role="form" method="post" action="">
                {% csrf_token %}

                <div class="card-body px-5 py-3">
                  <div class="row">
                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Username</label>
                        {{ form.username }}
                      </div>
                      <span class="text-danger">{{ form.username.errors }}</span>
                    </div>

                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Email</label>
                        {{ form.email }}
                      </div>
                      <span class="text-danger">{{ form.email.errors }}</span>
                    </div>

                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Password</label>
                        {{ form.password1 }}
                      </div>
                      <span class="text-danger">{{ form.password1.errors }}</span>
                    </div>

                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Password Check</label>
                        {{ form.password2 }}
                      </div>
                      <span class="text-danger">{{ form.password2.errors }}</span>
                    </div>
                  </div>
                </div>
                <div class="card-footer text-center">
                  {% if user.is_authenticated %}
                  <button type="submit" name="register" class="btn btn-fill btn-primary"
                    href="{% url 'login' %}">Salvar</button>
                  {% else %}
                  <button type="submit" name="register" class="btn btn-fill btn-primary">Registre-se</button>
                  <br /><br />
                  <p>
                    Ja tem uma conta?
                    <a href="{% url 'login' %}" class="text-primary">Login</a>
                  </p>
                  {% endif %}
                </div>
              </form>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}
  {% block javascripts %}{% endblock javascripts %}

usuario/templates/salvar_usuario.html
{% extends 'base.html' %} {% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="card">
  {% if not user.is_authenticated %}
  <h1>Registre - se</h1>
  {% endif %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
     {{ message }}
    </div>
  {% endfor %}
  {% if success %}
  <div class="card-footer text-center">
    <a href="{% url 'login' %}" class="btn btn-fill btn-primary">Login</a>
  </div>
  {% else %}
  <form role="form" method="post" action="" class="p-3">
    {% csrf_token %} {{ form.as_p }}
    <br />
    <div class="card-footer text-center">
      {% if user.is_authenticated %}
      <button
        type="submit"
        name="register"
        class="btn btn-fill btn-primary"
        href="{% url 'login' %}"
      >
        Salvar
      </button>
      {% else %}
      <button type="submit" name="register" class="btn btn-fill btn-primary">
        Registre-se
      </button>
      <br /><br />
      <p>
        Ja tem uma conta?
        <a href="{% url 'login' %}" class="text-primary">Login</a>
      </p>
      {% endif %}
    </div>
  </form>
  {% endif %}
</div>

{% endblock content %} {% block javascripts %}{% endblock javascripts %}

usuario/templates/side-bar.html
{% if user.is_authenticated %}
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
  <i class="fa-solid fa-bars"></i>
</button>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Todas Funções</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="dropdown mt-3">
      <ul class="d-flex flex-column list-group">
        <li><a href="{% url 'clientes:listar_clientes' %}" class="btn btn-primary list-group-item">Clientes</a></li>
        <li><a href="{% url 'emprestimo:listar_emprestimos' 'emprestimos_em_dia' %}" class="btn btn-primary list-group-item">Emprestimos</a></li>
          {% if user.is_superuser %}
            <li><a href="{% url 'home'%}" class="btn btn-primary list-group-item">Usuarios</a></li>
          {% endif %}
        <li><a href="{% url 'livros:listar_livros' %}" class="btn btn-fill btn-primary list-group-item">Livros</a></li>
        <li><a href="{% url 'logout' %}" class="btn btn-fill btn-primary list-group-item">Logout</a></li>
      </ul>
    </div>
  </div>
</div>
{% endif %}

usuario/templates/tables.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">Usuarios</h4>
    <td class="px-1"><a href="{% url 'salvar_usuario' %}" class="btn btn-primary btn-sm">Registrar Novo Usuario</a></td>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-dark table-striped-columns" id="">
        <thead class="text-primary">
          <tr>
            <th>Username</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <th>{{ user.username }}</th>
            <th>{{ user.email }}</th>
            <th><a type="submit" class="btn btn-primary" onclick="return confirm('Deseja realmente Deletar?')"
                href="{% url 'deletar_usuario' user.id %}">Delete</a></th>
            <th><a type="submit" class="btn btn-primary" href="{% url 'atualizar_usuario' user.id %}">Atualizar</a></th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}