emprestimo/urls.py
from django.urls import path
from .views import *


app_name = 'emprestimo'

urlpatterns = [
    path('listar_emprestimos/<str:filtro>', listar_emprestimos,name='listar_emprestimos'),
    path('registrar_novo_emprestimo/', registrar_novo_emprestimo,name='registrar_novo_emprestimo'),
    path('pesquisar_emprestimo/', pesquisar_emprestimo,name='pesquisar_emprestimo'),
    path('emprestimo/listar_emprestimos/deletar_emprestimo/<int:id>', deletar_emprestimo,name='deletar_emprestimo'),
    path('encerrar_emprestimo/<int:id>', encerrar_emprestimo,name='encerrar_emprestimo'),
    path('listar_emprestimos/todos_os_emprestimos', listar_emprestimos,name='pos_registro_emprestimo')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import urls as usuario_urls
from livro import urls as livros_urls
from clientes import urls as cliente_urls
from emprestimo import urls as emprestimo_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(usuario_urls)),
    path('livros/', include(livros_urls, namespace="livros")),
    path('cliente/', include(cliente_urls, namespace="cliente")),
    path('emprestimo/', include(emprestimo_urls, namespace="emprestimo")),      
]

livro/urls.py
from django.urls import path
from . import views


app_name = 'livros'

urlpatterns = [
    path('listar_livros/', views.listar_livros,name='listar_livros'),
    path('registrar_livro/', views.registrar_livro,name='registrar_livro'),
    path('pesquisar_livro/', views.pesquisar_livro,name='pesquisar_livro'),
    path('listar_livros/apagar_livro/<int:id>', views.apagar_livro,name='apagar_livro'),
    path('atualizar_livro/<int:id>', views.atualizar_livro,name='atualizar_livro'),
]

emprestimo/models.py
from django.db import models
from livro.models import livro
from clientes.models import Cliente

class Status_emprestimo(models.IntegerChoices):
        EM_DIA = 1,
        ATRASADO = 2,
        CONCLUIDO = 3
        
class Emprestimo(models.Model):
    
    livro = models.ForeignKey(livro, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data_emprestimo = models.DateField()
    data_devolucao = models.DateField()
    data_conclusao_emprestimo = models.DateField(null=True)
    status_emprestimo = models.IntegerField(default=Status_emprestimo.EM_DIA ,choices=Status_emprestimo.choices)

    def __str__(self):
        return f"Empréstimo de {self.livro} para {self.cliente}"



   

emprestimo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Emprestimo
from .models import Status_emprestimo
from clientes.models import Cliente
from livro.models import livro as Livro
import datetime


class RegistroEmprestimoForm(ModelForm):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.filter(pode_fazer_emprestimo=True),widget=forms.Select(attrs={'class': 'form-control'}))
    livro = forms.ModelChoiceField(queryset=Livro.objects.filter(esta_disponivel=True),widget=forms.Select(attrs={'class': 'form-control'}))
    data_emprestimo = forms.DateField(initial=datetime.date.today ,widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Selecione uma data', 'autocomplete': 'off','readonly':True}))
    data_devolucao = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Selecione uma data', 'autocomplete': 'off','value':''}))
    status_emprestimo = forms.ChoiceField(
        choices=Status_emprestimo.choices,
        widget=forms.Select(
            attrs={'class': 'form-control ','readonly':True}))
    class Meta:
        model = Emprestimo
        fields = ['cliente','livro','data_emprestimo','data_devolucao','status_emprestimo']

emprestimo/views.py
from django.shortcuts import render, redirect
from .forms import RegistroEmprestimoForm
from .models import Emprestimo
from livro.models import livro as Livro
from clientes.models import Cliente
from livro.forms import BuscarLivroForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import date

@login_required(login_url="login")
def listar_emprestimos(request,filtro="titulo_pesquisa"):
    try:
        emprestimos = None
        if filtro == "emprestimos_encerrados":
            emprestimos = Emprestimo.objects.filter(status_emprestimo=3)
        elif filtro == "emprestimos_atrasados":
            emprestimos = Emprestimo.objects.filter(status_emprestimo=2)
        elif filtro == "emprestimos_em_dia ":
            emprestimos = Emprestimo.objects.filter(status_emprestimo=1)
        elif filtro == "todos_os_emprestimos":
            emprestimos = Emprestimo.objects.all()
        elif filtro != "titulo_pesquisa" :
            emprestimos = Emprestimo.objects.filter(livro__titulo=filtro)
    except Exception as e:
         print(f" Exceção no Listar emprestimos {e}")

    return render(request,'listar_emprestimos.html',{'emprestimos':emprestimos, 'conteudo_pesquisa_form':BuscarLivroForm})

@login_required(login_url="login")
def registrar_novo_emprestimo(request):
    try:
        if request.method == 'POST':
            form = RegistroEmprestimoForm(request.POST)
            try:
                if form.is_valid():
                        if form.cleaned_data['cliente'].pode_fazer_emprestimo:
                            Cliente.objects.filter(id=form.cleaned_data['cliente'].id).update(pode_fazer_emprestimo = False)
                            Livro.objects.filter(id=form.cleaned_data['livro'].id).update(esta_disponivel = False)
                            form.save()
                        else:
                            messages.warning(request,"Cliente Não pode fazer emprestimos")
            except Exception as e:
                print(f" Exceção no Registrar novo emprestimo {e}")
                
                return redirect('emprestimo:pos_registro_emprestimo')
        else:
         form = RegistroEmprestimoForm()
    except Exception as e:
        print(f"Excecao no registrar novo emprestimo: {e}")

    return render(request, 'registro_emprestimo.html', {'form': form})

@login_required(login_url="login")
def pesquisar_emprestimo(request):
    titulo = None 
    if request.method == "POST":
        form = BuscarLivroForm(request.POST)
        if form.is_valid():
            try:
             titulo = form.cleaned_data.get("titulo")
            except Exception as e:
                print(f" Exceção no pesquisar emprestimo {e}")
            
    return listar_emprestimos(request,titulo)

@login_required(login_url="login")
def deletar_emprestimo(request,id):
    try:
        Emprestimo.objects.get(id=id).delete()
    except Exception as e:
        print(f" Exceção no deletar emprestimo {e}")

    return redirect('emprestimo:pos_registro_emprestimo')

@login_required(login_url="login")
def encerrar_emprestimo(request,id):
    try:
        emprestimo_encerrado = Emprestimo.objects.get(id=id)
        emprestimo_encerrado.status_emprestimo = 3
        Cliente.objects.filter(id=emprestimo_encerrado.cliente.id).update(pode_fazer_emprestimo = True)
        Livro.objects.filter(id=emprestimo_encerrado.livro.id).update(esta_disponivel=True)
        emprestimo_encerrado.data_conclusao_emprestimo = date.today()
        emprestimo_encerrado.save()
    except Exception as e:
        print(f" Exceção no eencerrar emprestimo {e}")
        
    return redirect('emprestimo:pos_registro_emprestimo')


@login_required(login_url="login")
def atualizar_disponibilidade_livro(id):
    try:
        livro_devolvido = Livro.objects.get(id=id)
        livro_devolvido.esta_disponivel = not livro_devolvido.esta_disponivel
        livro_devolvido.save()
    except Exception as e:
        print(f" Exceção no Atualizar Disponibilidade {e}")

@login_required(login_url="login")
def atualizar_habilitacao_emprestimo_cliente(id):
    try:
        cliente_para_atualizacao = Cliente.objects.get(id=id)
        cliente_para_atualizacao.pode_fazer_emprestimo = not cliente_para_atualizacao.pode_fazer_emprestimo
        cliente_para_atualizacao.save()
    except Exception as e:
        print(f" Exceção no Atualizar Habilitacao Cliente {e}")

emprestimo/templates/listar_emprestimos.html
{% extends 'base.html' %} 
{% block title %} Login {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="card">
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
          {{ message }}
    </div>
  {% endfor %}

  <div class="card-header">
    <h4 class="card-title">Emprestimos</h4>
  </div>
  <div class="card-body">
    <form method="POST" action="{% url 'emprestimo:pesquisar_emprestimo' %}" class="w-25 d-flex flex-row">
      {% csrf_token %} {{ conteudo_pesquisa_form }}
      <button type="submit" class="btn btn-fill btn-primary btn-sm">
        <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
    <td class="px-1"><a class="btn btn-primary btn-sm" href="{% url 'emprestimo:listar_emprestimos' 'emprestimos_encerrados' %}">Listar Concluidos</a></td>
    <td class="px-1"><a class="btn btn-primary btn-sm" href="{% url 'emprestimo:listar_emprestimos' 'emprestimos_atrasados' %}">Listar Atrasados</a></td>
    <td class="px-1"><a class="btn btn-primary btn-sm" href="{% url 'emprestimo:listar_emprestimos' 'emprestimos_em_dia ' %}">Listar Em Dia</a></td>
    <td class="px-1"><a class="btn btn-primary btn-sm" href="{% url 'emprestimo:listar_emprestimos' 'todos_os_emprestimos' %}">Ver Todos</a></td>
    <td class="px-1"><a href="{% url 'emprestimo:registrar_novo_emprestimo' %}" class="btn btn-primary btn-sm">Registrar Novo Emprestimo</a></td>
    <table class="table table-dark table-striped-columns">
      <thead>
        <tr>
          <th scope="col">Cliente</th>
          <th scope="col">Livro</th>
          <th scope="col">Data Emprestimo</th>
          <th scope="col">Devolução Prevista</th>
          <th scope="col">Status Emprestimo</th>
          <th scope="col">Data de Encerramento</th>
        </tr>
      </thead>
      <tbody>
        {% for emprestimo in emprestimos %}
            <tr>
                <td class="px-1">{{ emprestimo.cliente }}</td>
                <td class="px-1">{{ emprestimo.livro }}</td>
                <td class="px-1">{{ emprestimo.data_emprestimo }}</td>
                <td class="px-1">{{ emprestimo.data_devolucao }}</td>
                <td class="px-1">{{ emprestimo.get_status_emprestimo_display }}</td>

                {% if emprestimo.data_conclusao_emprestimo %}
                  <td class="px-1">{{ emprestimo.data_conclusao_emprestimo }}</td>
                {% else %}
                  <td class="px-1">Não Encerrado</td>
                {% endif %}

                {% if emprestimo.status_emprestimo == 3 %}
                <td class="px-1"><a class="btn btn-primary btn-sm" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'emprestimo:deletar_emprestimo' emprestimo.id %}">Apagar Emprestimo</a></td>
                {% else %}
                <td class="px-1"><a class="btn btn-primary btn-sm" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'emprestimo:deletar_emprestimo' emprestimo.id %}">Apagar Emprestimo</a></td>
                <td class="px-1"><a class="btn btn-primary btn-sm" onclick="return confirm('Confirmar Devolução?')" href="{% url 'emprestimo:encerrar_emprestimo' emprestimo.id %}">Encerrar Emprestimo</a></td>
                {% endif %}
            </tr>   
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %} {% block javascripts %}{% endblock javascripts %}

emprestimo/templates/registro_emprestimo.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="col-md-12">
    <div class="card m-auto">
      <div class="card-header">
        <h4 class="card-title">Salvar Emprestimo</h4>
      </div>
    <form class="d-flex flex-column w-75 ms-auto me-auto "  action="{% url 'emprestimo:registrar_novo_emprestimo'%}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="d-flex align-itens-center justify-content-center">
        <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
      </div>
    </form>
    </div>
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}