clientes/urls.py
from django.urls import path
from . import views


app_name = 'clientes'

urlpatterns = [
    path('listar_clientes/', views.listar_clientes,name='listar_clientes'),
    path('registrar_novo_cliente/', views.registrar_novo_cliente,name='registrar_novo_cliente'),
    path('pesquisar_cliente/', views.pesquisar_cliente,name='pesquisar_cliente'),
    path('cliente/cliente/listar_clientes/deletar_cliente/<int:id>', views.deletar_cliente,name='deletar_cliente'),
    path('atualizar_cliente/<int:id>', views.atualizar_cliente,name='atualizar_cliente'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import urls as usuario_urls
from livro import urls as livros_urls
from clientes import urls as cliente_urls
from emprestimo import urls as emprestimo_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(usuario_urls)),
    path('livros/', include(livros_urls, namespace="livros")),
    path('cliente/', include(cliente_urls, namespace="cliente")),
    path('emprestimo/', include(emprestimo_urls, namespace="emprestimo")),      
]

livro/urls.py
from django.urls import path
from . import views


app_name = 'livros'

urlpatterns = [
    path('listar_livros/', views.listar_livros,name='listar_livros'),
    path('registrar_livro/', views.registrar_livro,name='registrar_livro'),
    path('pesquisar_livro/', views.pesquisar_livro,name='pesquisar_livro'),
    path('listar_livros/apagar_livro/<int:id>', views.apagar_livro,name='apagar_livro'),
    path('atualizar_livro/<int:id>', views.atualizar_livro,name='atualizar_livro'),
]

clientes/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    data_nascimento = models.DateField()
    endereco = models.CharField(max_length=200)
    cpf = models.CharField(max_length=14,unique=True)
    telefone = models.CharField(max_length=30,default=9999-9999)
    pode_fazer_emprestimo = models.BooleanField(default=True)

    def __str__(self):
        return (f"Cliente {self.nome} cpf {self.cpf}")

clientes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cliente

class ClienteForm(ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Nome","class": "form-control"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"placeholder": "Email","class": "form-control"}))
    cpf = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Cpf","class": "form-control",'min':14,'max':14}))
    data_nascimento = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    endereco = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Endereço","class": "form-control"}))
    telefone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Telefone","class": "form-control"}))
    class Meta:
        model = Cliente
        fields = ['nome','email','cpf','data_nascimento','endereco','telefone']

class BuscaClienteNomeForm(forms.Form):
    nome_cliente = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Informe o nome do Cliente","class": "form-control"}))

clientes/views.py
from django.shortcuts import render, redirect
from .models import Cliente
from . import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from emprestimo.models import Emprestimo
from django.contrib import messages

@login_required(login_url="login")
def listar_clientes(request,aviso_ao_usuario="",nome_cliente="listar_todos"):
    
    clientes=None
    try:
        if nome_cliente == "listar_todos":
            clientes = Cliente.objects.all()
        else:
            clientes = Cliente.objects.filter(nome__startswith=nome_cliente)
    except Exception as e:
        print(f" excecao no listar clientes {e}")

    nome_cliente_para_filtrar = forms.BuscaClienteNomeForm()

    return render(request,"listar_clientes.html",{'clientes':clientes ,'nome_cliente_para_filtrar':nome_cliente_para_filtrar})

@login_required(login_url="login")
def registrar_novo_cliente(request):
    if request.method == "POST":
        form_cliente = forms.ClienteForm(request.POST)
        if form_cliente.is_valid():
            try:
                obj_cliente = form_cliente.save(commit=False)
                if Cliente.objects.filter(email=obj_cliente.email).exists() \
                and Cliente.objects.filter(cpf=obj_cliente.email).exists():
                    aviso_ao_usuario = "Email já ou Cpf já cadastrado"
                    return listar_clientes(request, aviso_ao_usuario=aviso_ao_usuario)
                else:
                    obj_cliente.save()
                    aviso_ao_usuario = "Cliente Salvo Com Sucesso"
                    return redirect('clientes:listar_clientes')
            except Exception as e:
                print(f" excecao no registrar novo cliente {e}")
    else:
        form_cliente = forms.ClienteForm() 
    return render(request, 'registrar_novo_cliente.html', {'form_cliente': form_cliente})

 
@login_required(login_url="login")  
def deletar_cliente(request, id):
    if request.method == "GET":
        try:
            obj_cliente = Cliente.objects.get(id=id)
            if obj_cliente.pode_fazer_emprestimo:
                obj_cliente.delete()
                messages.success(request, "Apagado com sucesso.")
            else:
                messages.warning(request, "Não é possivel apagar clientes com débitos.")
            
        except Exception as e:
            print(f"Excecao no deletar cliente {e}")
           
    return listar_clientes(request)
    

@login_required(login_url="login")   
def atualizar_cliente(request,id):
    cliente = None
    if request.method == "POST":
        try:
            cliente = Cliente.objects.get(id=id)
            form = forms.ClienteForm(request.POST or None, instance=cliente)
            if form.is_valid():
                form.save() 
                return redirect('clientes:listar_clientes')
        except Exception as e:
            print(f"Excecao no atualizar cliente {e}")
            
    else:
         return render(request,'atualizar_cliente.html',{'form':form})  
        
@login_required(login_url="login") 
def pesquisar_cliente(request):
    nome_cliente = None
    try:
        if request.method == "POST":
            form_busca_cliente_nome = forms.BuscaClienteNomeForm(request.POST)
            if form_busca_cliente_nome.is_valid():
                nome_cliente = form_busca_cliente_nome.cleaned_data.get("nome_cliente")
                print(nome_cliente)
    except Exception as e:
        print(f"Excecao no pesquisar cliente {e}")
    return listar_clientes(request,nome_cliente=nome_cliente)

clientes/templates/atualizar_cliente.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="card ">
<h1 class="mt-3 ms-3">Atualizar Cliente</h1>
</br>
<form class="mt-2 ms-4 vw-50" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <div class="d-flex justify-content-center">
        <input type="submit" onclick="return confirm('Deseja Realmente Atualizar?')" value="Atualizar" class="btn btn-primary btn-sm">
    </div>
</form>
</div>
{% endblock content %} {% block javascripts %}{% endblock javascripts %}

clientes/templates/listar_clientes.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
{% load l10n %}

<div class="card">
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
    {{ message }}
    </div>
  {% endfor %}
  <div class="card-header">
    <h4 class="card-title">Clientes</h4>
  </div>
    <form method="POST" action="{% url 'clientes:pesquisar_cliente' %}" class="w-25 d-flex flex-row">
      {% csrf_token %} 
      {{ nome_cliente_para_filtrar }}
      <button type="submit" class="btn btn-fill btn-primary btn-sm">
        <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
    <div class="vw-25">
      <a class="btn btn-primary btn-sm" href="{% url 'clientes:registrar_novo_cliente' %}">Registrar Novo Cliente</a>
    </div>
    <table class="table table-dark table-striped-columns table-hover">
      <thead>
        <tr class="px-1">
          <th scope="col">Nome</th>
          <th scope="col">Email</th>
          <th scope="col">Data Nascimento</th>
          <th scope="col">Endereço</th>
          <th scope="col">Telefone</th>
          <th scope="col">Situação</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for cliente in clientes %}
        <tr>
          <td class="px-1">{{ cliente.nome }}</td>
          <td class="px-1">{{ cliente.email }}</td>
          <td class="px-1">{{ cliente.data_nascimento |date:"d/m/Y" }}</td>
          <td class="px-1">{{ cliente.endereco }}</td>
          <td class="px-1">{{ cliente.telefone }}</td>
          {% if cliente.pode_fazer_emprestimo %}
          <td class="px-1">Nada Consta</td>
          {% else %}
          <td class="px-1">Cliente Com Débito</td>
          {% endif %}
          {% if user.is_superuser %}
            <td class="px-1"><a class="btn btn-primary btn-sm" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'clientes:deletar_cliente' cliente.id %}">Delete</td>
            <td class="px-1"><a class="btn btn-primary btn-sm" href="{% url 'clientes:atualizar_cliente' cliente.id %}">Atualizar</td>
          {% else %}
            <td class="px-1"><a disabled="true" class="btn btn-primary btn-sm" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'clientes:deletar_cliente' cliente.id %}">Delete</td>
            <td class="px-1"><a disabled="true" class="btn btn-primary btn-sm" href="{% url 'clientes:atualizar_cliente' cliente.id %}">Atualizar</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %} {% block javascripts %}{% endblock javascripts %}

clientes/templates/registrar_novo_cliente.html
{% extends 'base.html' %} {% block title %} Login {% endblock %}  
{% block stylesheets %}{% endblock stylesheets %} {% block content %}
<div class="card" >
  <div class="card-header">
    <h4 class="card-title">Clientes</h4>
  </div>
  <div class="card-body">
    <form role="form" method="post" action="{% url 'clientes:registrar_novo_cliente' %}">
      {% csrf_token %}
        <td>{{ form_cliente.as_p }}</td>
      </div>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary btn-sm">Salvar</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block javascripts %}{% endblock javascripts %}