library/urls.py
from django.contrib import admin
from django.urls import path, include
from usuario import urls as usuario_urls
from livro import urls as livros_urls
from clientes import urls as cliente_urls
from emprestimo import urls as emprestimo_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(usuario_urls)),
    path('livros/', include(livros_urls, namespace="livros")),
    path('cliente/', include(cliente_urls, namespace="cliente")),
    path('emprestimo/', include(emprestimo_urls, namespace="emprestimo")),      
]

livro/urls.py
from django.urls import path
from . import views


app_name = 'livros'

urlpatterns = [
    path('listar_livros/', views.listar_livros,name='listar_livros'),
    path('registrar_livro/', views.registrar_livro,name='registrar_livro'),
    path('pesquisar_livro/', views.pesquisar_livro,name='pesquisar_livro'),
    path('listar_livros/apagar_livro/<int:id>', views.apagar_livro,name='apagar_livro'),
    path('atualizar_livro/<int:id>', views.atualizar_livro,name='atualizar_livro'),
]

livro/models.py
from django.db import models

class livro(models.Model):
    titulo = models.CharField(max_length=30)
    autor = models.CharField(max_length=30)
    descricao = models.CharField(max_length=200)
    isbn = models.CharField(max_length=20,unique=True)
    esta_disponivel = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo

livro/forms.py
from django import forms
from django.forms import ModelForm
from .models import livro as Livro

class LivroForm(ModelForm):
    titulo = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Titulo","class": "form-control"}))
    autor = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Autor","class": "form-control"}))
    descricao = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Descrição","class": "form-control"}))
    isbn = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "ISBN",
        "class": "form-control",
        'type':'number',
        'maxlength': 17}))
    esta_disponivel = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={}),initial=True)
    class Meta:
        model = Livro
        fields = ['titulo','autor','descricao','isbn','esta_disponivel']
    
class BuscarLivroForm(forms.Form):
    titulo = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Buscar Por Titulo","class": "form-control"}))

livro/views.py
from django.shortcuts import render,redirect
from .models import livro as Livro
from . import forms
from django.contrib.auth.decorators import login_required

@login_required(login_url="login")
def listar_livros(request,msg="",titulo_livro="sem_pesquisa"):
    try:
        if titulo_livro == "sem_pesquisa":
            livros = Livro.objects.all()
        else:
            livros = Livro.objects.filter(titulo__startswith=titulo_livro)
        conteudo_pesquisa_form = forms.BuscarLivroForm()
    except Exception as e:
        print(f"Excecao no listar_livros {e}")
        
    return render(request,"listar_livros.html",{'livros':livros ,'msg':msg,'conteudo_pesquisa_form':conteudo_pesquisa_form})

@login_required(login_url="login")
def registrar_livro(request):
    try:
        if request.method == "POST":
            form = forms.LivroForm(request.POST)
            if form.is_valid():
                titulo = form.cleaned_data.get("titulo")
                autor = form.cleaned_data.get("autor")
                descricao = form.cleaned_data.get("descricao")
                isbn = form.cleaned_data.get("isbn")
                esta_disponivel = True
                livro_obj = None
                try:
                    livro_obj = Livro.objects.get(titulo=titulo)    
                except Exception as e:
                    print(e)
                    
                if livro_obj:
                    msg = "Livro já existe"
                    return listar_livros(request, {"msg": msg})
                else:
                    livro_obj = Livro.objects.create(titulo=titulo, autor=autor, descricao=descricao, isbn=isbn, esta_disponivel=esta_disponivel)
                    msg = "Salvo com sucesso"
                return listar_livros(request, {"msg": msg})
        else:
            form = forms.LivroForm()
    except Exception as e:
        print(f"Excecao no registrar_livros {e}")
    return render(request,'registrar_livro.html',{'form':form})
    
@login_required(login_url="login") 
def apagar_livro(request, id):
    try:    
        if request.method == "GET":
            try:
                livro_obj = Livro.objects.get(id=id)
                livro_obj.delete()
            except Exception as e:
                print(e)
            return listar_livros(request)
    except Exception as e:
        print(f"Excecao no apagar_livros {e}")

    
@login_required(login_url="login")
def atualizar_livro(request,id):
    try:    
        obj_livro = None
        obj_livro = Livro.objects.get(id=id)
        form = forms.LivroForm(request.POST or None, instance=obj_livro)
        if request.method == "POST":
            if form.is_valid():
                form.save() 
                return redirect('livros:listar_livros')
    except Exception as e:
        print(f"Excecao no atualizar_livros {e}")
        
    return render(request,'atualizar_livro.html',{'form':form})
    
    
@login_required(login_url="login")
def pesquisar_livro(request):
    try:
        if request.method == "POST":
            form = forms.BuscarLivroForm(request.POST)
            if form.is_valid():
                titulo = form.cleaned_data.get("titulo")
    except Exception as e:
        print(f"Excecao no pesquisar_livros {e}")    
    return listar_livros(request,titulo_livro=titulo)
    

livro/templates/atualizar_livro.html
{% extends 'base.html' %} {% block title %} Login {% endblock %}
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="card p-5">
  <h4>Atualizar Livro</h4>
  <form action="" method="post">
    {% csrf_token %} {{ form.as_p }}
    <br />
    <input
      type="submit"
      onclick="return confirm('Deseja realmente Atualizar?')"
      value="Atualizar"
      class="btn btn-primary"
    />
  </form>
</div>
{% endblock content %} {% block javascripts %}{% endblock javascripts %}

livro/templates/listar_livros.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Livros</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <form method="POST" action="{% url 'livros:pesquisar_livro' %}" class="w-25 d-flex flex-row">
                                    {% csrf_token %}
                                    {{ conteudo_pesquisa_form }}
                                    <button type="submit" class="btn btn-fill btn-primary btn-sm">
                                        <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                                    </button>
                                </form>
                                <td class="px-1"><a href="{% url 'livros:registrar_livro' %}" class="btn btn-fill btn-primary btn-sm">Adicionar Novo Livro</a></td>
                                <table class="table table-dark table-striped-columns">
                                    <thead>
                                        <tr>
                                            <th scope="col">Titulo</th>
                                            <th scope="col">Autor</th>
                                            <th scope="col">Descrição</th>
                                            <th scope="col">ISBN</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for livro in livros %}
                                        <tr>
                                            <td class="col-1">{{ livro.titulo }}</td>
                                            <td class="col-1">{{ livro.autor }}</td>
                                            <td class="col-1">{{ livro.descricao }}</td>
                                            <td class="col-1">{{ livro.isbn }}</td>
                                            {% if user.is_superuser %}
                                            <td><a type="submit" class="btn btn-fill btn-primary"  href="{% url 'livros:atualizar_livro' livro.id%}">Atualizar</a></td>
                                            <th><a type="submit" class="btn btn-fill btn-primary" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'livros:apagar_livro' livro.id %}">Delete</th>
                                            {% else %}
                                            <td><a disabled="true" type="submit" class="btn btn-fill btn-primary"  href="{% url 'livros:atualizar_livro' livro.id%}">Atualizar</a></td>
                                            <th><a disabled="true" type="submit" class="btn btn-fill btn-primary" onclick="return confirm('Deseja realmente Deletar?')" href="{% url 'livros:apagar_livro' livro.id %}">Delete</th>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

livro/templates/register_book.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

<div class="content">
      <div class="container">
        <div class="row pt-5">
          <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
            <div class="card">

              <form role="form" method="post" action="">
                {% csrf_token %}

                <div class="card-body px-5 py-3">
                  <div class="row">
                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Titulo</label>
                        {{ form.titulo }}
                      </div>
                      <span class="text-danger">{{ form.titulo.errors }}</span>
                    </div>

                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Autor</label>
                        {{ form.authors }}
                      </div>
                      <span class="text-danger">{{ form.authors.errors }}</span>
                    </div>
                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>Descrição</label>
                        {{ form.descricao }}
                      </div>
                      <span class="text-danger">{{ form.descricao.errors }}</span>
                    </div>
                    <div class="col-md-12 px-md-1">
                      <div class="form-group">
                        <label>ISBN</label>
                        {{ form.isbn }}
                      </div>
                      <span class="text-danger">{{ form.isbn.errors }}</span>
                    </div>
                  </div>
                  <button type="submit" name="register" class="btn btn-fill btn-primary">Salvar</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}
  {% block javascripts %}{% endblock javascripts %}

livro/templates/registrar_livro.html
{% extends 'base.html' %} {% block title %} Registrar Novo Livro {% endblock %}
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="card p-5">
  <form role="form" class="vw-75" method="post" action="{% url 'livros:registrar_livro' %}">
    {% csrf_token %} {{ form.as_p }}
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary bnt-sm">Salvar</button>
    </div>
  </form>
</div>
<script>
  function validarIsbn(){
    const inputIsbn = Document.getElementById('id_isbn');
    const isbn = inputIsbn.value;

    const isbnClened = isbn.replace(/[-\s]/g, '');

    if (/^\d{10}$/.test(cleanedISBN) || /^\d{13}$/.test(cleanedISBN)) {
        alert('ISBN válido');
    } else {
        alert('ISBN inválido');
    }
}
</script>
{% endblock content %}
{% block javascripts %}
{% endblock javascripts %}

livro/templates/show_collection.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %} 
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Livros</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <form method="POST" action="{% url 'livros:pesquisar_livro' %}" class="w-25 d-flex flex-row">
                                    {% csrf_token %}
                                    {{ conteudo_pesquisa_form }}
                                    <button type="submit" class="btn btn-fill btn-primary">
                                        <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                                    </button>
                                </form>
                                <table class="table table-striped-columns">
                                    <thead>
                                        <tr>
                                            <th scope="col">Titulo</th>
                                            <th scope="col">Autor</th>
                                            <th scope="col">Descrição</th>
                                            <th scope="col">ISBN</th>
                                            <th scope="col">Disponibilidade</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for livro in livros %}
                                        <tr>
                                            <td>{{ livro.titulo }}</td>
                                            <td>{{ livro.authors }}</td>
                                            <td>{{ livro.descricao }}</td>
                                            <td>{{ livro.isbn }}</td>
                                            {% if livro.esta_disponivel %}
                                            <td>Disponivel</td>
                                            <td><a class="btn btn-fill btn-primary">Reservar</a></td>
                                            <th><a type="submit" class="btn btn-fill btn-primary"
                                                    href="delete/{{ livro.id }}">Delete</th>
                                            {% else %}
                                            <td>Indisponivel</td>
                                            <td><a type="hidden" disabled class="btn btn-fill btn-primary">Reservar</a></td>
                                            <th><a type="hidden" disabled class="btn btn-fill btn-primary" href="delete/{{ livro.id }}">Delete</th>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}